### PR TITLE
enable JIRA API v2 with new optional JIRA version command line argument

### PR DESCRIPTION
**Pull request by dkoltaimyob**
Adding support for JIRA API v2.
Using an optional parameter, if not provided, defaults to using the current url.

### CODE REVIEW

**Comment by Regenhardt** [comment]
Why not default to "latest" and then just append that to the path?

**Comment by Regenhardt** [comment]
OTOH should the user even care about which version the tool uses? What's the use case here?

**Comment by garfieldonthemoon** [comment]
Hi @Regenhardt thanks for the feedback. This is not relevant any more, seems it was required back then probably because of this issue: https://jira.atlassian.com/browse/JRACLOUD-72126

Please close the PR.

(Note: I am the one who opened this PR back then, but don't any more have access to that handle, so no permission to close it.)

**Comment by Regenhardt** [comment]
I'm just a guy who used this script in his time of need, @pawelrychlik could close it though :)

**Pull request closed without merging**
